name: Run Volume Bot Daily
on:
  workflow_dispatch:   # lets you run manually from the Actions tab
  schedule:
    - cron: "55 17 * * *"   # 23:38 IST daily
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install yfinance pandas requests pytz
      - name: Run bot
        env: 
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
