name: 15-min Intraday Scanner

# Run every 15 minutes + manual trigger
on:
  schedule:
    - cron: '*/15 * * * *'  # GitHub Actions uses UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests

      # Step 4: Run the scanner
      - name: Run Intraday Scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python intraday_15min_scanner.py
