name: Stock Confluence Alerts

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "45,0,15,30,45 5-9 * * 1-5"
    - cron: "0 10 * * 1-5"

jobs:
  run-stock-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests pytz

      - name: Run stock_alert.py (manual or scheduled)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MANUAL_RUN: ${{ github.event_name == 'workflow_dispatch' }}
        run: python stock_alert.py
