name: Stock Confluence Alerts

on:
  workflow_dispatch: # allows manual run
  schedule:
    - cron: '15 10-15 * * 1-5' # every 15 mins from 10:15 to 15:15, Mon-Fri (adjust for market hours)

jobs:
  send_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run stock alert
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python stock_alert.py
