name: Stock Confluence Alerts

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    # Runs every 15 minutes between 11:15 AM to 3:30 PM IST
    - cron: '0,15,30,45 5-10 * * 1-5' # UTC times (IST = UTC+5:30)

jobs:
  stock_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run Stock Alert Script
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python stock_alert.py
