name: Stock Confluence Alerts

on:
  workflow_dispatch: # allows manual run
  schedule:
    # Every 15 minutes from 9:30–15:30 IST (4:00–10:00 UTC), Mon-Fri
    - cron: '0,15,30,45 4-9 * * 1-5'
    - cron: '0 10 * * 1-5'

jobs:
  send_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run stock alert
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python stock_alert.py
